# Generated by Django 3.0.8 on 2020-07-28 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20200728_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
